version: '3'
services:
  ##
  ## Postgress SQL
  ## Dados apenas para uso local
  ##
  pgsql:
    image: postgres:12
    container_name: laravel_toolbox_db
    volumes:
      - './db:/var/lib/postgres'
    environment:
      POSTGRES_PASSWORD: '123456'
      POSTGRES_USER: laravel_toolbox
      POSTGRES_DB: laravel_toolbox
    ports:
      - "5434:5432"
  php:
    container_name: laravel_toolbox_web
    build:
      context: ./php
    ports:
      - '8080:80'
    volumes:
      - './src:/var/www/html'
    depends_on:
      - pgsql